openapi: 3.0.3
info:
  title: QuickShort API
  version: 1.0.0
servers:
  - url: https://go.codequesthub.io
paths:
  /v1/links:
    post:
      summary: Create short link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                target: { type: string, format: uri }
                slug: { type: string }
                expires_at: { type: integer, format: int64, description: epoch seconds }
              required: [target]
      responses:
        '201':
          description: Created
        '400': { description: Bad Request }
        '409': { description: Slug exists }
  /{slug}:
    get:
      summary: Resolve short link
      parameters:
        - in: path
          name: slug
          required: true
          schema: { type: string }
      responses:
        '301': { description: Redirect }
        '404': { description: Not found }
