name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable, override: true }
      - name: Install cargo-lambda
        run: cargo install cargo-lambda --locked
      - name: Build Lambda artifact
        run: cargo lambda build --release --arm64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: us-east-1
      - name: Terraform Init
        working-directory: deployments/terraform
        run: terraform init
      - name: Terraform Apply
        working-directory: deployments/terraform
        env:
          TF_VAR_domain_name: codequesthub.io
          TF_VAR_subdomain: go
          TF_VAR_aws_region_lambda: us-west-2
        run: terraform apply -auto-approve
